spring:
  application:
    name: apiforge

  datasource:
    url: jdbc:postgresql://localhost:5433/apiforge
    username: apiforge
    password: apiforge123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  security:
    jwt:
      secret: apiforge-secret-key-change-in-production
      expiry: 86400000

server:
  port: 8080

logging:
  level:
    com.apiforge: DEBUG