spring:
  application:
    name: apiforge

  datasource:
    url: jdbc:postgresql://35.200.160.109:5432/apiforge
    username: satyam
    password: 030405@Saira
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-init-sql: SET TIME ZONE 'UTC'

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC

  docker:
    compose:
      enabled: false
  ai:
    google:
      genai:
        api-key: AIzaSyBT48JIIk3gUEzKzXKRV4YxpqXgh7epJgg
        project-id: garodiatraders
        chat:
          options:
            model: gemini-2.5-flash-lite


server:
  port: 8080

logging:
  level:
    com.satyam: DEBUG